# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: cd build && ls
    - run: ls
    - name: SFTP Deploy
      # You may pin to the exact commit or the version.
      # uses: wlixcc/SFTP-Deploy-Action@fe288f8e0f466f9567fb3e54434b41800cc7b880
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        # username
        username: gitupload
        # your sftp server
        server: 45.136.31.229
        # your sftp server port, default to 22
        port: 22
        # you can copy private_key from your *.pem file, keep format
        ssh_private_key: ${{ secrets.PRIVATEKEY }}
        # will put all file under this path
        local_path: /build/
        # files will copy to under remote_path
        remote_path: /home/lars/apollo-frontend/
 
